name: Continuous Integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.can_fail }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        rust: [beta, stable]
        can_fail: [true]
        include:
          - os: ubuntu-latest
            rust: stable
            can_fail: false
          - os: ubuntu-latest
            rust: beta
            can_fail: false
    steps:
      # Linux dependencies
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libpango1.0-dev libatk1.0-dev libgtk-3-dev libappindicator3-dev

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libpango1.0-dev libatk1.0-dev libgtk-3-dev libappindicator3-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
